Char_None,          // NUL
Char_None,          // SOH
Char_None,          // STX
Char_None,          // ETX
Char_None,          // EOT
Char_None,          // ENQ
Char_None,          // ACK
Char_None,          // BEL
Char_None,          // BS
Char_Whitespace,    // HT
Char_Whitespace,    // LF
Char_None,          // VT
Char_None,          // FF
Char_None,          // CR
Char_None,          // SO
Char_None,          // SI
Char_None,          // DLE
Char_None,          // DC1
Char_None,          // DC2
Char_None,          // DC3
Char_None,          // DC4
Char_None,          // NAK
Char_None,          // SYN
Char_None,          // ETB
Char_None,          // CAN
Char_None,          // EM
Char_None,          // SUB
Char_None,          // ESC
Char_None,          // FS
Char_None,          // GS
Char_None,          // RS
Char_None,          // US
Char_Whitespace,    // SP
Char_Mathematic,    // !
Char_Symbolic,      // "
Char_Symbolic,      // #
Char_Symbolic,      // $
Char_Mathematic,    // %
Char_Mathematic,    // &
Char_Symbolic,      // '
Char_Symbolic,      // (
Char_Symbolic,      // )
Char_Mathematic,    // *
Char_Mathematic,    // +
Char_Symbolic,      // ,
Char_Mathematic,    // -
Char_Symbolic,      // .
Char_Mathematic,    // /
Char_Numeric,       // 0
Char_Numeric,       // 1
Char_Numeric,       // 2
Char_Numeric,       // 3
Char_Numeric,       // 4
Char_Numeric,       // 5
Char_Numeric,       // 6
Char_Numeric,       // 7
Char_Numeric,       // 8
Char_Numeric,       // 9
Char_Mathematic,    // :
Char_Mathematic,    // ;
Char_Mathematic,    // <
Char_Mathematic,    // =
Char_Mathematic,    // >
Char_Mathematic,    // ?
Char_Symbolic,      // @
Char_Alphabetic,    // A
Char_Alphabetic,    // B
Char_Alphabetic,    // C
Char_Alphabetic,    // D
Char_Alphabetic,    // E
Char_Alphabetic,    // F
Char_Alphabetic,    // G
Char_Alphabetic,    // H
Char_Alphabetic,    // I
Char_Alphabetic,    // J
Char_Alphabetic,    // K
Char_Alphabetic,    // L
Char_Alphabetic,    // M
Char_Alphabetic,    // N
Char_Alphabetic,    // O
Char_Alphabetic,    // P
Char_Alphabetic,    // Q
Char_Alphabetic,    // R
Char_Alphabetic,    // S
Char_Alphabetic,    // T
Char_Alphabetic,    // U
Char_Alphabetic,    // V
Char_Alphabetic,    // W
Char_Alphabetic,    // X
Char_Alphabetic,    // Y
Char_Alphabetic,    // Z
Char_Symbolic,      // [
Char_Symbolic,      // \ ---
Char_Symbolic,      // ]
Char_Mathematic,    // ^
Char_Underscore,    // _
Char_Symbolic,      // `
Char_Alphabetic,    // a
Char_Alphabetic,    // b
Char_Alphabetic,    // c
Char_Alphabetic,    // d
Char_Alphabetic,    // e
Char_Alphabetic,    // f
Char_Alphabetic,    // g
Char_Alphabetic,    // h
Char_Alphabetic,    // i
Char_Alphabetic,    // j
Char_Alphabetic,    // k
Char_Alphabetic,    // l
Char_Alphabetic,    // m
Char_Alphabetic,    // n
Char_Alphabetic,    // o
Char_Alphabetic,    // p
Char_Alphabetic,    // q
Char_Alphabetic,    // r
Char_Alphabetic,    // s
Char_Alphabetic,    // t
Char_Alphabetic,    // u
Char_Alphabetic,    // v
Char_Alphabetic,    // w
Char_Alphabetic,    // x
Char_Alphabetic,    // y
Char_Alphabetic,    // z
Char_Symbolic,      // {
Char_Mathematic,    // |
Char_Symbolic,      // }
Char_Mathematic,    // ~
Char_None,          // DEL
